### ISSUE TITLE
ValueError: Couldn't parse datetime string

### ISSUE THREAD

**Issue by eldamir** [Deepwalker/aldjemy#35]
All I did was add `aldjemy` to my installed apps and then try `MyModel.query().all()`

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2399, in all
    return list(self)
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 71, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 428, in _instance
    loaded_instance, populate_existing, populators)
  File "/home/ruben/v3env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
    dict_[key] = getter(row)
ValueError: Couldn't parse datetime string 'b'2015-07-15 11:07:40.037679'' - value is not a string.
```

**Comment by Deepwalker** [comment]
sqlite?

**Comment by eldamir** [comment]
yup. For development purposes

**Comment by Deepwalker** [comment]
try 0.4.2

**Comment by Deepwalker** [comment]
BTW if you plan to deploy your application to use other database in production – use some database for development.
