### ISSUE TITLE
Breaks on Django 1.9

### ISSUE THREAD

**Issue by adambrenecki** [Deepwalker/aldjemy#36]
Hi,

When using Aldjemy 0.4.3 with Django 1.9 I get the following error:

```
Traceback (most recent call last):
  File "/opt/pycharm-5/helpers/pycharm/django_test_manage.py", line 53, in <module>
    django.setup()
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/aldjemy/apps.py", line 17, in ready
    prepare_models()
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/aldjemy/orm.py", line 86, in prepare_models
    tables = get_tables()
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/aldjemy/core.py", line 67, in get_tables
    generate_tables(get_meta())
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/aldjemy/table.py", line 79, in generate_tables
    typ = DATA_TYPES[internal_type](field)
  File "/home/adam/.virtualenvs/fleetv2/local/lib/python2.7/site-packages/aldjemy/types.py", line 19, in foreign_key
    parent_model = field.related.model
AttributeError: 'ManyToOneRel' object has no attribute 'related'
```

**Comment by Deepwalker** [comment]
Can you check 0.5.0-rc1?

**Comment by ygavenchuk** [comment]
Hi.
I have the same problem with:

aldjemy==0.4.3
Django==1.9
SQLAlchemy==1.0.11

**Comment by Deepwalker** [comment]
Ok, so will release then. Its hard to keep this project alive, since I does not work with django for a long time.

**Comment by Deepwalker** [comment]
releases 0.5.0 to pypi.
