### ISSUE TITLE
Issue with mapping when using UUID fields

### ISSUE THREAD

**Issue by fearofcode** [Deepwalker/aldjemy#40]
I have a Django 1.9 model called `Property` (I know it clashes with the Python keyword `property`, but it doesn't effect the issue I'm having).

When I put `aldjemy` in Django's app list and tried to open up the Django shell, I got this stack trace:

```
$ ./bin/manage shell_plus
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python3.5/site-packages/aldjemy/apps.py", line 17, in ready
    prepare_models()
  File "/usr/local/lib/python3.5/site-packages/aldjemy/orm.py", line 114, in prepare_models
    orm.mapper(sa_models[name], table, attrs)
  File "<string>", line 2, in mapper
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 629, in __init__
    self._configure_pks()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/mapper.py", line 1223, in _configure_pks
    (self, self.mapped_table.description))
sqlalchemy.exc.ArgumentError: Mapper Mapper|Property|core_property could not assemble any primary key columns for mapped table 'core_property'
```

`core` is our Django application name and `core_property` is the table of the model in question.

I believe this UUID field is causing the issue:

```Python
id = models.UUIDField(primary_key=True, default=uuid.uuid4)
```

Commenting this line allows the shell to load successfully.

So is there something about UUID fields or non-auto primary key fields that would make aldjemy error out this way?

Is there anything we can do besides not use a UUID primary key field?

Thanks!

**Comment by fearofcode** [comment]
Django 1.9, aldjemy 0.6.0, Python 3.5 in case that helps.

**Comment by fearofcode** [comment]
I think I've fixed it. All I had to do was overwrite `ALDJEMY_DATA_TYPES`:

```Python
from sqlalchemy.dialects.postgresql import UUID

ALDJEMY_DATA_TYPES = {
    'UUIDField': lambda field: UUID()
}
```
